### ISSUE TITLE
Menu desaparece algunas veces

### ISSUE THREAD

**Issue by YerkoPalma** [proinchile/proinchile.github.io#6]
El problema es super especifico y un poco rebuscado. Se da cuando aparece el boton para el menu mobile, y se presiona. Si luego de eso redimensiono la pantalla, no se ve el menu principal. Al parecer, despues de que se muestra el menu mobile, por alguna razón el div con la clase `head-right` queda con `width` y `height` 0 (como se ve en la [**imagen**](http://prntscr.com/8uhep6))

**Comment by DiruzCode** [comment]
Gracias yerko y disculpa la demora en responder, lo revisaremos para ver que ocurre, quizas se cambie la web también andamos en busca de algún template para poder integrar.


Saludos
